name: horizontal_barcode_scanner
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/rafaelmaia8384/horizontal_barcode_scanner

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera: ^0.10.5+5
  google_mlkit_barcode_scanning: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.horizontal_barcode_scanner
        pluginClass: HorizontalBarcodeScannerPlugin
      ios:
        pluginClass: HorizontalBarcodeScannerPlugin
